version: "3.7"

services:
  database_filimo:
    image: postgres
    container_name: clickideia
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=wilk1998
      - POSTGRES_DB=clickideia
    volumes:
      - pgdata:/data/postgres
    # network_mode: host
  app:
    build: .
    container_name: clickideia
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    # network_mode: host

volumes:
  pgdata:
    driver: local
