version: "3.7"

services:
  db_clickideia:
    image: postgres
    container_name: db_clickideia
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=wilk1998
      - POSTGRES_DB=db_clickideia
    volumes:
      - pgdata:/data/postgres
    # network_mode: host
  app:
    build: .
    container_name: clickideia
    restart: always
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    # network_mode: host

volumes:
  pgdata:
    driver: local
